version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-default}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-default}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-default}
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./wp:/var/www/html
      - ./external-themes/sample-theme:/var/www/html/wp-content/themes/sample-theme
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME:-default}
      MYSQL_USER: ${WORDPRESS_DB_USER:-default}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD:-default}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u$WORDPRESS_DB_USER", "-p$WORDPRESS_DB_PASSWORD"]

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 10080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      db:
        condition: service_healthy

  cli:
    image: wordpress:cli
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-default}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-default}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-default}
    volumes:
      - ./wp:/var/www/html
    user: xfs
    command: bash -c "
      wp --allow-root core install
        --url=https://${CODESPACE_NAME}-8080.githubpreview.dev
        --title=Sandbox
        --admin_user=${WORDPRESS_ADMIN_USER}
        --admin_password=${WORDPRESS_ADMIN_PASSWORD}
        --admin_email=${WORDPRESS_ADMIN_EMAIL}
        --skip-email
      && wp --info"
    depends_on:
      - db
      - wordpress

volumes:
  db:
